### ISSUE TITLE
go get -u google.golang.org/api/storage is the wrong import

### ISSUE THREAD

**Issue by dhilton** [GoogleCloudPlatform/storage-getting-started-go#4]
Installing the storage client as explained in the README.md fails due to the fact the library has moved to a versioned url:

```
go get -u google.golang.org/api/storage
package google.golang.org/api/storage
	imports google.golang.org/api/storage
	imports google.golang.org/api/storage: no buildable Go source files
```

Append /v1 and all is good:
```
go get -u google.golang.org/api/storage/v1
```
However, when you change to this new version you also need to change the scope definition to:

```golang
        scope      = "https://www.googleapis.com/auth/devstorage.full_control"

```
Doing these two changes enabled me to run the example.

**Comment by gmlewis** [comment]
Thanks for the report!
Fixed.  Closing.
